version: '3'

services:
  traefik:
    # The official v2.9 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.<ENV-NAME>-user-<ENV-USER-ID>-02.<ENV-ANIMAL>.<ENV-DOMAIN>`)"
  flask:
    # A container that exposes an API to show its IP address
    image: ghcr.io/infralovers/training-flask-app:v1
    labels:
      - "traefik.http.routers.flask.rule=Host(`flask.<ENV-NAME>-user-<ENV-USER-ID>-02.<ENV-ANIMAL>.<ENV-DOMAIN>`)"
