
services:
  reverse-proxy:
    # The official v3.2 Traefik docker image
    image: traefik:v3.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`host.<ENV-NAME>-user-<ENV-USER-ID>-02.<ENV-ANIMAL>.<ENV-DOMAIN>`)"
      - "traefik.http.middlewares.whoami-basicauth.basicauth.users=coder:$$2y$$05$$MJwyPJgYDe4uNRpFZZ74c.1MuwagBU4jSV44weFRf.PzpQNIPYyAK"
      - "traefik.http.routers.whoami.middlewares=whoami-basicauth"
  flask:
    # A container that exposes an API to show its IP address
    image: commandemy/flask
    labels:
      - "traefik.http.routers.flask.rule=Host(`server.<ENV-NAME>-user-<ENV-USER-ID>-02.<ENV-ANIMAL>.<ENV-DOMAIN>`)"
