version: "3.3"

services:

  api:
    image: commandemy/12-factor-app:v0.1
    env_file: docker-compose.env
    environment:
      SERVICES: api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.12factor.rule=Host(`server.cno-user-XX-i-02.commandemy.training`)"
    networks:
      - internal
  
  products:
    image: commandemy/12-factor-app:v0.1
    env_file: docker-compose.env
    environment:
      SERVICES: products
    depends_on:
      - mongo
    networks:
      - internal

  nats:
    image: 'nats:2.1'
    networks:
      - internal

  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    networks:
      - internal

  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  data:
